### ISSUE TITLE
Question int32_t

### ISSUE THREAD

**Issue by gagagu** [jmriego/Fino#28]
Hi,
thanks for your work.
I'm building an Arduino FFB Yoke based also an your work (see https://github.com/gagagu/Arduino_FFB_Yoke).

Atm. I'm working on version 1.3 with many code changes and I also need to reduce the programm memory size, atm. I'm using 94% (27218 bytes) of my Arduino Micro. I'm looking for possibilities of reduce the size and found out, that using the datatype int16_t instead of int32_t, in all code lines (include yours) is saving  3% (1006 Bytes) of program memory and would also make the software faster because of less execution time.

I know that int32_t has a bigger value size but 16 bit should be enough for what we are doing, or not?
I would like to know what you thinking about this?

Thx forward

**Comment by jmriego** [comment]
sure thing! It's always nice to see people using it

To be honest, I'm in a similar situation and was doing a cleanup of some variables as I'm trying to add a PID controller so the spring effect can be slightly better and avoid oscillations.
So this is great timing. Yes, you are right, those variables can be changed to int16_t as most of the numbers go from -10000 to 10000. The reason is that the original code that I based this from used int32_t as they allowed any number range you wanted, but I set it to -10000,10000 to follow the Force Feedback USB standards.

I'll have to review in case there's any variable that can exceed that range but I cannot imagine there would be any

**Comment by gagagu** [comment]
Hi, thx for reply. 
I have changes all datatypes and now i have some % more programcode free. 

Whats about to reduce the spring gain to avoid oscillations?
I'm working on a new code to adjust all gains and effect parameters (max friction, max acceleration and damper max velocity) by a windows app and save it to to the eeprom to load it on next startup.
With this you are able to make different adjustments for different games/planes.

Thx

**Comment by jmriego** [comment]
the oscillation is something that happens eventually for every force feedback joystick if you increase the forces high enough, but this can be improved upon using a PID controller which depends on position, movement speed, etc. and tends to correct better.

Other things I want to do to make the code smaller are:
1. Stop using floats
2. Change sin/cos values to be stored in EEPROM instead of calculated in code
3. Make the HID for USB to be stored in EEPROM instead of calculated in every device start

Storing things in EEPROM would make it a bit more difficult to flash the device as you would need the first flash to record in the EEPROM and then remove the EEPROM recording code and flash again

Not sure if you saw this code, but there's already some sample code on transferring configuration variables through Serial that you might be able to use https://github.com/jmriego/Fino/blob/master/com.ino#L57

**Comment by gagagu** [comment]
Thx, i will keep an Eye on your project.

**Comment by Hitman86R** [comment]
Hi, sorry, is the project still maintained? I'm also trying to build my joystick, given the amount of code I opted for Arduino Due, but on the other hand it has a relatively low speed compared to an ESP32, so I too would be interested in reducing the weight of the library. there is not much material around for such a project, in my opinion keeping this repo active is fundamental

**Comment by gagagu** [comment]
I have changed int32_t to int16_t and everything is working without any issues. 
Removing floats will also reduce many programm code but its not easy to do that.
To pre-write eeprom values is may be simple by using the serial interface. You can implement an serial command like „write to eeprom“ with parameter of address, and value and write it direct from pc to eeprom.
It would be very simple to implement in my code but stop using floats would be a massive benefit.

**Comment by jmriego** [comment]
hi @Hitman86R ! Yes, this is being maintained but doesn't require much changes at the moment. As far as I can see, everything work perfectly but the improvements are more on the side of making the library slimmer. I really want to keep this repo active as this is the only one I've seen where all the types of forces work correctly on two axes.
I'm also working on a PID controller to compare against a basic spring effect, but I cannot see any improvement with the joystick I'm using.

By the way, I don't think you'll see any need to reduce the code if using an Arduino Due unless I'm missing something. You should have plenty of space and I think this code should go up to 1000 "FPS" or complete force calculations per second on that hardware.

**Comment by Hitman86R** [comment]
@jmriego , I have done many other projects with arduino and similar, but this is my first experience with peripherals that interface directly with the operating system and therefore I am trying to acquire as much information as possible in this regard, I also manage fairly well with python and qt , in fact I'm tempted to create (in the future when everything will be clear to me) also a management interface for the joystick.
As motors I will use two JMC iHSV57-30-18-36, and I have to understand how to make them interact correctly with the library, I state that I can read and write the motor parameters via modbus rs232 protocol. I don't want to go further off topic as this is not a dedicated section, although I would like to discuss it with you and others.
To answer your last question, yes it is true that arduino due has everything I need to complete my project, but looking around I read of someone who has also used an esp32 for such a project which with its 240Mhz (compared to the 84Mhz of Arduino Due) you have a much quicker response especially if you have to manage many parameters, obviously to the detriment of the GPIOs. It remains only an idea however, for now my project remains on Arduino Due.

**Comment by jmriego** [comment]
I just merged #29 after reviewing all changes to int16 and I only had to keep a few of them for the ApplyEnvelope as it's doing several multiplications and divisions that required a bit more precision. Without that, the sine waves and several types of shakes were not working correctly.

@Hitman86R if you want, you can reach me in the [HOTAS/HOSAS/SIMPIT Discord server](https://discord.gg/szqaJE7). I'll be happy to chat about that

**Comment by Hitman86R** [comment]
@jmriego, Thanks for the invite, yesterday I joined the discord server.

**Comment by GO63-samara** [comment]
I have checked this PR: https://github.com/jmriego/Fino/tree/int16
https://github.com/jmriego/Fino/pull/29/commits/9e09d4a388d786e1e9abb132d9480e1cc9059f25
Confirm, this saves 890 bytes in PROGMEM.
Well done!
